"""Reconcile AP18B-03 authored cells with the source's native Excel features.

Default input: .work/ap18b-03/structure. --batch selects the batch directory.
--batch-05 reconciles the declared V0.11 calendar-condition extension only.
No dates, legal data, formulas, or cell values are generated by this adapter.
The declared patches and artifact-export.xlsx supply all changed cell content.
"""
from copy import deepcopy
from pathlib import Path
from urllib.parse import urlparse
import hashlib
import json
import posixpath
import re
import sys
import xml.etree.ElementTree as ET
import zipfile

ROOT = Path(__file__).resolve().parents[1]
N = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
R = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'
P = 'http://schemas.openxmlformats.org/package/2006/relationships'
NS = {'s': N}
T = '{' + N + '}'


def require(condition, *context):
    if not condition:
        raise AssertionError(context)


def read(file):
    with zipfile.ZipFile(file) as archive:
        require(archive.testzip() is None, 'ZIP integrity', str(file))
        require(len(archive.namelist()) == len(set(archive.namelist())), 'duplicate ZIP members')
        return {name: archive.read(name) for name in archive.namelist()}


def xml(node):
    ET.register_namespace('', node.tag.split('}')[0].lstrip('{'))
    ET.register_namespace('r', R)
    return ET.tostring(node, encoding='utf-8', xml_declaration=True)


def pool(parts):
    return [''.join(e.itertext()) for e in ET.fromstring(parts['xl/sharedStrings.xml'])] if 'xl/sharedStrings.xml' in parts else []


def indices(address):
    match = re.fullmatch(r'\$?([A-Z]+)\$?([1-9]\d*)', address)
    require(match is not None, 'invalid A1 address', address)
    column = 0
    for letter in match[1]:
        column = column * 26 + ord(letter) - 64
    return column, int(match[2])


def letters(column):
    result = ''
    while column:
        column, remainder = divmod(column - 1, 26)
        result = chr(65 + remainder) + result
    return result


def rectangles(reference):
    for area in reference.split():
        ends = area.split(':')
        require(len(ends) in (1, 2), 'invalid range', reference)
        left, top = indices(ends[0])
        right, bottom = indices(ends[-1])
        require(left <= right and top <= bottom, 'reversed range', reference)
        yield left, top, right, bottom


def addresses(reference):
    return {f'{letters(c)}{r}' for left, top, right, bottom in rectangles(reference)
            for r in range(top, bottom + 1) for c in range(left, right + 1)}


def sheet_map(parts):
    rels = {e.get('Id'): (e.get('Target').lstrip('/') if e.get('Target').startswith('/')
                        else posixpath.normpath('xl/' + e.get('Target')))
            for e in ET.fromstring(parts['xl/_rels/workbook.xml.rels'])}
    return {e.get('name'): rels[e.get('{' + R + '}id')]
            for e in ET.fromstring(parts['xl/workbook.xml']).find('s:sheets', NS)}


def canonical(cell, strings):
    out = deepcopy(cell)
    if out.get('t') == 's':
        value = strings[int(out.find('s:v', NS).text)]
        for child in list(out):
            out.remove(child)
        out.set('t', 'inlineStr')
        text = ET.SubElement(ET.SubElement(out, T + 'is'), T + 't')
        text.text = value
        if value != value.strip():
            text.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
    return out


def signature(node):
    if node is None:
        return None
    return (node.tag, tuple(sorted(node.attrib.items())), node.text or '',
            tuple(signature(child) for child in node))


def cell_text(cell, strings):
    if cell is None:
        return ''
    value = canonical(cell, strings)
    if value.get('t') == 'inlineStr':
        return ''.join(value.find('s:is', NS).itertext())
    return value.findtext('s:v', default='', namespaces=NS)


def extend(reference, old, new):
    # Extend only a bottom boundary, never a top anchor or embedded formula.
    return re.sub(r'(:\$?[A-Z]+\$?)' + str(old) + r'(?=$|\s)',
                  lambda match: match[1] + str(new), reference)


def set_width(sheet, column, width):
    cols = sheet.find('s:cols', NS)
    if cols is None:
        cols = ET.Element(T + 'cols')
        sheet.insert(list(sheet).index(sheet.find('s:sheetData', NS)), cols)
    replacement, found = [], False
    for current in cols:
        start, end = int(current.get('min')), int(current.get('max'))
        if start <= column <= end:
            if start < column:
                left = deepcopy(current)
                left.set('max', str(column - 1))
                replacement.append(left)
            middle = deepcopy(current)
            middle.attrib.update(min=str(column), max=str(column), width=str(width), customWidth='1')
            replacement.append(middle)
            if column < end:
                right = deepcopy(current)
                right.set('min', str(column + 1))
                replacement.append(right)
            found = True
        else:
            replacement.append(current)
    if not found:
        replacement.append(ET.Element(T + 'col', {'min': str(column), 'max': str(column),
                                                'width': str(width), 'customWidth': '1'}))
    cols[:] = sorted(replacement, key=lambda c: int(c.get('min')))


def migrate_validations(sheet, authored_sheet, end):
    allowed = {9, 10, 11, 12, 27}
    source = sheet.find('s:dataValidations', NS)
    require(source is not None, 'source rule validations missing')
    # Split a multi-column native range if only part is being replaced.
    preserved = []
    for validation in source:
        ranges = []
        for left, top, right, bottom in rectangles(validation.get('sqref')):
            for column in range(left, right + 1):
                if column not in allowed:
                    ranges.append(f'{letters(column)}{top}:{letters(column)}{bottom}')
        if ranges:
            kept = deepcopy(validation)
            kept.set('sqref', ' '.join(ranges))
            preserved.append(kept)
    expected = {f'{letters(c)}{r}' for c in allowed for r in range(7, end + 1)}
    candidates = []
    for validation in authored_sheet.findall('s:dataValidations/s:dataValidation', NS):
        ranges = list(rectangles(validation.get('sqref')))
        columns = {c for left, _, right, _ in ranges for c in range(left, right + 1)}
        if not columns.intersection(allowed):
            continue
        require(columns <= allowed, 'authored validation overlaps unrelated columns', validation.get('sqref'))
        cells = addresses(validation.get('sqref'))
        require(cells <= expected, 'authored validation exceeds authorized body', validation.get('sqref'))
        full_range = all(top == 7 and bottom == end for _, top, _, bottom in ranges)
        stop_alert = (validation.get('errorStyle', 'stop') == 'stop'
                      and validation.get('showErrorMessage') in ('1', 'true')
                      and bool(validation.get('error', '').strip()))
        candidates.append((validation, cells, full_range and stop_alert))
    imported, coverage = [], set()
    for validation, cells, authorized in candidates:
        if not authorized:
            continue
        require(not cells.intersection(coverage), 'ambiguous full-range stop validations', validation.get('sqref'))
        imported.append(deepcopy(validation))
        coverage.update(cells)
    # Artifact may retain an old I7:I122 rule beside the new I7:I198 rule.
    # Discard stale/weak overlaps only after complete full-range stop coverage
    # has been proven. Never retain two competing validations for one input.
    require(expected == coverage, 'missing full-range stop validation coverage', sorted(expected - coverage)[:10])
    require(all(cells <= coverage for _, cells, _ in candidates), 'uncovered stale validation')
    source[:] = preserved + imported
    source.set('count', str(len(source)))


def append_condition_validation(sheet, authored_sheet, end):
    """Preserve every extended source rule and import only authored AB validation."""
    source = sheet.find('s:dataValidations', NS)
    require(source is not None, 'source rule validations missing')
    expected = addresses(f'AB7:AB{end}')
    for validation in source:
        require(not addresses(validation.get('sqref')).intersection(expected),
                'source condition validation must not exist', validation.get('sqref'))
    candidates = []
    for validation in authored_sheet.findall('s:dataValidations/s:dataValidation', NS):
        ranges = list(rectangles(validation.get('sqref')))
        if not any(left <= 28 <= right for left, _, right, _ in ranges):
            continue
        require(ranges == [(28, 7, 28, end)], 'unexpected authored condition validation range',
                validation.get('sqref'))
        require(validation.get('type') == 'list'
                and validation.get('errorStyle', 'stop') == 'stop'
                and validation.get('showErrorMessage') in ('1', 'true')
                and bool(validation.get('error', '').strip())
                and bool(validation.findtext('s:formula1', default='', namespaces=NS).strip()),
                'condition validation must be an authored list with stop alert')
        candidates.append(validation)
    require(len(candidates) == 1, 'exactly one authored condition validation required', len(candidates))
    preserved = [signature(item) for item in source]
    source.append(deepcopy(candidates[0]))
    source.set('count', str(len(source)))
    require([signature(item) for item in list(source)[:-1]] == preserved,
            'existing rule validations changed while adding condition validation')


def verify_condition_native_features(old, new, spec, name):
    """Check the narrow structural delta independently of cell patch coverage."""
    expected = deepcopy(old.find('s:dataValidations', NS))
    if expected is not None:
        for item in expected:
            item.set('sqref', extend(item.get('sqref'), spec['oldEnd'], spec['end']))
    actual = new.find('s:dataValidations', NS)
    if name == 'Feiertagsregeln':
        require(expected is not None and actual is not None, 'rule validations missing')
        require(len(actual) == len(expected) + 1, 'native condition validation count mismatch')
        require([signature(item) for item in list(actual)[:-1]] == [signature(item) for item in expected],
                'pre-existing rule validations changed')
    else:
        require(signature(expected) == signature(actual), 'validation changed beyond extension', name)
    expected_cf = deepcopy(old.findall('s:conditionalFormatting', NS))
    for item in expected_cf:
        item.set('sqref', extend(item.get('sqref'), spec['oldEnd'], spec['end']))
    require([signature(item) for item in expected_cf]
            == [signature(item) for item in new.findall('s:conditionalFormatting', NS)],
            'conditional formatting changed beyond bottom extension', name)
    expected_cols = deepcopy(old)
    if name == 'Feiertagsregeln':
        set_width(expected_cols, 28, 38)
    require(signature(expected_cols.find('s:cols', NS)) == signature(new.find('s:cols', NS)),
            'column dimensions changed beyond AB width', name)


def main():
    require(set(sys.argv[1:]) <= {'--batch', '--batch-04', '--batch-05'},
            'supported arguments: --batch, --batch-04, --batch-05')
    conditions = '--batch-05' in sys.argv
    require(not conditions or set(sys.argv[1:]) == {'--batch-05'}, '--batch-05 cannot be combined with older modes')
    rest = '--batch-04' in sys.argv
    qa = (ROOT / '.work/ap18b-05' if conditions else
          ROOT / ('.work/ap18b-04' if rest else '.work/ap18b-03') / ('batch' if rest or '--batch' in sys.argv else 'structure'))
    checks = json.loads((qa / 'checks.json').read_text())
    source, final = Path(checks['source']), Path(checks['file'])
    require(source.resolve() != final.resolve(), 'source must not be overwritten')
    source_sha = hashlib.sha256(source.read_bytes()).hexdigest()
    require(source_sha == checks['sourceSha256'], 'source SHA mismatch')
    if conditions:
        require(source_sha == '37d33d4639cc839fc41c9850de8e6551d546167fe8b9ee7f10ea5f2c062d99fd',
                'batch-05 must use the immutable V0.11 reference')
        require(not checks.get('sourceUrls'), 'batch-05 must preserve existing source hyperlinks')
    before, authored = read(source), read(qa / 'artifact-export.xlsx')
    parts = dict(before)
    src_pool, out_pool = pool(before), pool(authored)
    src_sheets, out_sheets = sheet_map(before), sheet_map(authored)
    require(src_sheets.keys() == out_sheets.keys() and len(src_sheets) == 9, 'sheet contract changed')
    specs = {spec['name']: spec for spec in checks['specs']}
    require(len(specs) == len(checks['specs']), 'duplicate specs')
    targets = {}
    for patch in checks['patches']:
        require(patch['name'] in src_sheets, 'unknown patch sheet', patch['name'])
        targets.setdefault(patch['name'], set()).update(addresses(patch['range']))
    require({'Feiertagsregeln', 'Feiertagskalender'} <= specs.keys(), 'missing structural table specs')
    if conditions:
        require(set(specs) == {'Feiertagsregeln', 'Feiertagskalender', 'Quellenprüfung'},
                'batch-05 permits only three structural specs')
        require(len({spec['tableName'] for spec in specs.values()}) == 3,
                'batch-05 structural table names must be distinct')
        for name, old_end, new_end in [('Feiertagsregeln', 480, 485), ('Feiertagskalender', 489, 494),
                                        ('Quellenprüfung', 91, 96)]:
            require((specs[name]['oldEnd'], specs[name]['end']) == (old_end, new_end),
                    'batch-05 row boundaries changed', name)
        require(specs['Quellenprüfung']['last'] == 'K', 'review table width changed')
        require(addresses('A92:K96') <= targets.get('Quellenprüfung', set()),
                'all appended review cells must be declared')
        require(not targets.get('Quellenprüfung', set()).intersection(addresses('A7:K91')),
                'historical source reviews must not be edited')
    for name, last in [('Feiertagsregeln', 'AB' if conditions else 'AA'), ('Feiertagskalender', 'O')]:
        spec = specs[name]
        require(spec['last'] == last and 7 <= spec['oldEnd'] <= spec['end'], 'invalid structural spec', name)
        first = 6 if conditions and name == 'Feiertagsregeln' else spec['oldEnd'] + 1 if rest or conditions else 6
        require(addresses(f'{last}{first}:{last}{spec["end"]}') <= targets.get(name, set()), 'new column/cells must be wholly declared', name)
    changed_parts = set()
    styles = ET.fromstring(before['xl/styles.xml']).find('s:cellXfs', NS)

    for name, changed in targets.items():
        key = src_sheets[name]
        sheet = ET.fromstring(before[key])
        data = sheet.find('s:sheetData', NS)
        old_cells = {c.get('r'): c for c in sheet.findall('s:sheetData/s:row/s:c', NS)}
        rows = {int(row.get('r')): row for row in data}
        authored_sheet = ET.fromstring(authored[out_sheets[name]])
        author_cells = {c.get('r'): c for c in authored_sheet.findall('s:sheetData/s:row/s:c', NS)}
        author_rows = {int(row.get('r')): row for row in authored_sheet.find('s:sheetData', NS)}
        spec = specs.get(name)
        moving_helpers = name == 'Feiertagsregeln' and cell_text(old_cells.get('AA6'), src_pool) != 'Tagesumfang'
        if conditions and name == 'Feiertagsregeln':
            require(not moving_helpers, 'batch-05 must not move Easter helpers')
            require(not changed.intersection(addresses('AC6:AD23')), 'batch-05 Easter helper changes are not permitted')
            require(cell_text(author_cells.get('AB6'), out_pool) == 'Kalenderbedingung',
                    'authored condition header missing')
        if moving_helpers:
            require(addresses('AA6:AB23') | addresses('AC6:AD23') <= changed, 'helper relocation must be declared')
        for address in sorted(changed, key=lambda a: (indices(a)[1], indices(a)[0])):
            column, row_number = indices(address)
            existing = old_cells.get(address)
            appended = spec and spec['oldEnd'] < row_number <= spec['end'] and column <= indices(spec['last'] + '1')[0]
            template_row = (spec['oldEnd'] if row_number % 2 == spec['oldEnd'] % 2 else spec['oldEnd'] - 1) if appended else row_number
            template = old_cells.get(f'{letters(column)}{template_row}')
            if conditions and name == 'Feiertagsregeln' and column == 28 and 6 <= row_number <= spec['end']:
                template = old_cells.get(f'AA{template_row}')
                require(template is not None, 'native condition style template missing', address)
            elif not rest and not conditions and name == 'Feiertagsregeln' and column == 27 and 6 <= row_number <= spec['end']:
                template = old_cells.get('Z6' if row_number == 6 else f'L{template_row}')
            elif name == 'Feiertagsregeln' and moving_helpers and column in (29, 30) and 6 <= row_number <= 23:
                template = old_cells.get(f'{letters(column - 2)}{row_number}')
            elif not rest and not conditions and name == 'Feiertagskalender' and column == 15 and 6 <= row_number <= spec['end']:
                template = old_cells.get('N6' if row_number == 6 else f'L{template_row}')
            elif name == 'Gebietszuordnungen' and column == 1 and 'notesStart' in checks and checks['notesStart'] <= row_number <= checks['notesStart'] + 4:
                template = old_cells.get(f'A{checks.get("sourceNotesStart", 15) + row_number - checks["notesStart"]}')
            cell = canonical(author_cells.get(address, ET.Element(T + 'c', {'r': address})), out_pool)
            if template is not None and 's' in template.attrib:
                cell.set('s', template.get('s'))
            else:
                cell.attrib.pop('s', None)
            if cell.find('s:f', NS) is not None:
                protection = styles[int(cell.get('s', '0'))].find('s:protection', NS)
                require(protection is None or protection.get('locked', '1') in ('1', 'true'), 'formula would be unlocked', name, address)
            row = rows.get(row_number)
            if row is None:
                # Only safe row dimensions, never imported style IDs or outline state.
                row = ET.Element(T + 'row', {'r': str(row_number)})
                rows[row_number] = row
            if existing is not None and existing in list(row):
                row.remove(existing)
            row.append(cell)
        for rn, row in rows.items():
            row[:] = sorted(row, key=lambda cell: indices(cell.get('r'))[0])
            if spec and spec['oldEnd'] < rn <= spec['end'] and rn in author_rows:
                for attribute in ('ht', 'customHeight'):
                    if attribute in author_rows[rn].attrib:
                        row.set(attribute, author_rows[rn].get(attribute))
        data[:] = [rows[rn] for rn in sorted(rows)]
        if spec:
            for item in sheet.findall('s:dataValidations/s:dataValidation', NS) + sheet.findall('s:conditionalFormatting', NS):
                item.set('sqref', extend(item.get('sqref'), spec['oldEnd'], spec['end']))
        if name == 'Feiertagsregeln':
            if conditions:
                append_condition_validation(sheet, authored_sheet, spec['end'])
                set_width(sheet, 28, 38)
            else:
                migrate_validations(sheet, authored_sheet, spec['end'])
                for column, width in [(27, 22), (28, 3), (29, 22), (30, 18)]:
                    set_width(sheet, column, width)
        elif not conditions and name == 'Feiertagskalender':
            for column, width in [(2, 30), (15, 22)]:
                set_width(sheet, column, width)
        dimension = sheet.find('s:dimension', NS)
        if dimension is not None:
            maximum = max(indices(cell.get('r'))[0] for row in rows.values() for cell in row)
            dimension.set('ref', f'A1:{letters(maximum)}{max(rows)}')
        parts[key] = xml(sheet)
        changed_parts.add(key)

    table_count = 0
    matched_specs = set()
    for key, value in before.items():
        if not (key.startswith('xl/tables/') and key.endswith('.xml')):
            continue
        table_count += 1
        table = ET.fromstring(value)
        spec = next((item for item in specs.values() if item['tableName'] == table.get('name')), None)
        if spec is None:
            continue
        columns = table.find('s:tableColumns', NS)
        name = spec['name']
        require(not conditions or name not in matched_specs, 'duplicate native table spec match', name)
        matched_specs.add(name)
        original_columns = [signature(column) for column in columns]
        if conditions:
            if name == 'Feiertagsregeln':
                require(len(columns) == 27 and table.get('ref') == 'A6:AA480',
                        'unexpected V0.11 rule table contract')
                require('28' not in {column.get('id') for column in columns}, 'condition column ID collision')
                ET.SubElement(columns, T + 'tableColumn', {'id': '28', 'name': 'Kalenderbedingung'})
                columns.set('count', '28')
                require([signature(column) for column in list(columns)[:-1]] == original_columns,
                        'existing native table columns changed')
                require(columns[-1].attrib == {'id': '28', 'name': 'Kalenderbedingung'},
                        'condition native table column mismatch')
            elif name == 'Feiertagskalender':
                require(len(columns) == 15 and table.get('ref') == 'A6:O489',
                        'unexpected V0.11 calendar table contract')
            else:
                require(name == 'Quellenprüfung' and len(columns) == 11 and table.get('ref') == 'A6:K91',
                        'unexpected V0.11 review table contract')
            require([signature(column) for column in list(columns)[:len(original_columns)]] == original_columns,
                    'pre-existing native table columns changed', name)
        elif name in ('Feiertagsregeln', 'Feiertagskalender'):
            count = 27 if name == 'Feiertagsregeln' else 15
            require(len(columns) in (count - 1, count), 'unexpected native table width', name)
            if len(columns) == count - 1:
                require(str(count) not in {c.get('id') for c in columns}, 'new native column ID collision', name)
                ET.SubElement(columns, T + 'tableColumn', {'id': str(count), 'name': 'Tagesumfang'})
            require(columns[-1].get('id') == str(count), 'unexpected day-portion column ID', name)
            columns[-1].set('name', 'Tagesumfang')
            columns.set('count', str(count))
            if name == 'Feiertagsregeln':
                columns[11].set('name', 'Tagesabstand')
        table.set('ref', f'A6:{spec["last"]}{spec["end"]}')
        table.find('s:autoFilter', NS).set('ref', table.get('ref'))
        current = ET.fromstring(parts[src_sheets[name]])
        cells = {c.get('r'): c for c in current.findall('s:sheetData/s:row/s:c', NS)}
        require(len(columns) == indices(spec['last'] + '1')[0], 'table column count mismatch', name)
        for index, column in enumerate(columns, 1):
            require(column.get('name') == cell_text(cells.get(f'{letters(index)}6'), src_pool), 'table/header mismatch', name, index)
        parts[key] = xml(table)
        changed_parts.add(key)
    require(not conditions or matched_specs == set(specs), 'structural spec has no matching native table')

    if checks.get('sourceUrls'):
        key = src_sheets['Rechtsquellen']
        sheet = ET.fromstring(parts[key])
        links = sheet.find('s:hyperlinks', NS)
        require(links is not None, 'native source hyperlink container missing')
        rel_key = posixpath.dirname(key) + '/_rels/' + posixpath.basename(key) + '.rels'
        rels = ET.fromstring(parts[rel_key])
        for row, url in enumerate(checks['sourceUrls'], 7):
            require(urlparse(url).scheme == 'https' and urlparse(url).netloc, 'HTTPS source URL required', row)
            address = f'E{row}'
            link = next((item for item in links if item.get('ref') == address), None)
            if link is None:
                rid = f'ap18b03Source{row}'
                require(rid not in {r.get('Id') for r in rels}, 'hyperlink ID collision', rid)
                link = ET.SubElement(links, T + 'hyperlink', {'ref': address, '{' + R + '}id': rid})
                ET.SubElement(rels, '{' + P + '}Relationship', {'Id': rid, 'Type': R + '/hyperlink', 'Target': url, 'TargetMode': 'External'})
            else:
                relation = next(r for r in rels if r.get('Id') == link.get('{' + R + '}id'))
                relation.set('Target', url)
        parts[key], parts[rel_key] = xml(sheet), xml(rels)
        changed_parts.update((key, rel_key))

    unchanged = 0
    for name, key in src_sheets.items():
        old, new = ET.fromstring(before[key]), ET.fromstring(parts[key])
        old_cells = {c.get('r'): c for c in old.findall('s:sheetData/s:row/s:c', NS)}
        new_cells = {c.get('r'): c for c in new.findall('s:sheetData/s:row/s:c', NS)}
        for address in old_cells.keys() | new_cells.keys():
            if address in targets.get(name, set()):
                continue
            require(address in old_cells and address in new_cells, 'undeclared cell insertion/removal', name, address)
            require(signature(canonical(old_cells[address], src_pool)) == signature(canonical(new_cells[address], src_pool)), 'undeclared cell change', name, address)
            unchanged += 1
        require(not new.findall('.//s:c[@t="e"]', NS), 'cached formula error', name)
        if conditions and name in specs:
            verify_condition_native_features(old, new, specs[name], name)
        if conditions and name == 'Feiertagsregeln':
            for row_number in range(7, 481):
                address = f'W{row_number}'
                require(signature(old_cells[address].find('s:f', NS)) == signature(new_cells[address].find('s:f', NS)),
                        'pre-existing raw date formula changed', address)
        for native in ('sheetProtection', 'sheetViews', 'mergeCells', 'tableParts'):
            require(signature(old.find('s:' + native, NS)) == signature(new.find('s:' + native, NS)), 'native feature changed', name, native)
    require(parts['xl/styles.xml'] == before['xl/styles.xml'], 'source styles changed')
    require(not conditions or table_count == 8, 'batch-05 native table count changed')
    require(parts.keys() == before.keys(), 'package members changed')
    require(not any('vbaProject' in key or key == 'xl/connections.xml' for key in parts), 'unexpected macros/connections')
    require(all(parts[key] == value for key, value in before.items() if key not in changed_parts), 'undeclared native part changed')
    require(hashlib.sha256(source.read_bytes()).hexdigest() == source_sha, 'source changed during reconciliation')
    final.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(final, 'w', zipfile.ZIP_DEFLATED) as archive:
        for key, value in parts.items():
            archive.writestr(key, value)
    require(read(final) == parts, 'saved package readback mismatch')
    require(hashlib.sha256(source.read_bytes()).hexdigest() == source_sha, 'source changed while saving final workbook')
    audit = {'sha256': hashlib.sha256(final.read_bytes()).hexdigest(), 'sourceSha256': source_sha,
             'sourceUnchanged': True, 'unchangedCellsOutsideDeclaredEdits': unchanged,
             'stylePartIdentical': True, 'nativePartsOutsideDeclaredEditsIdentical': True,
             'sheets': len(src_sheets), 'tables': table_count,
             'rules': specs['Feiertagsregeln']['end'] - 6,
             'calendarRows': specs['Feiertagskalender']['end'] - 6,
             'sourceHyperlinks': (len(ET.fromstring(parts[src_sheets['Rechtsquellen']]).findall('s:hyperlinks/s:hyperlink', NS))
                                  if conditions else len(checks.get('sourceUrls', []))),
             'nativeExcelUiTest': 'notPerformed'}
    if conditions:
        audit.update(conditionColumn='AB', conditionColumnHeader='Kalenderbedingung',
                     nativeRuleValidationsPreserved=True, oldRawDateFormulasPreserved=True,
                     easterHelpersPreserved=True, sourceHyperlinksPreserved=True,
                     ruleTableColumnCount=28, historicalSourceReviewsPreserved=True,
                     sourceReviewRows=specs['Quellenprüfung']['end'] - 6)
    (qa / 'native-audit.json').write_text(json.dumps(audit, indent=2) + '\n')
    print(json.dumps(audit))


if __name__ == '__main__':
    main()
